### ISSUE TITLE
ModTweaker2 0.9.1 Changelog

### ISSUE THREAD

**Issue by Zixxl** [jaredlll08/ModTweaker2#186]
Just to keep track of all changes, should be easier to write changelogs after release.

Forestry
- [x] Update Centrifuge handlers for Forestry 3.6.0+ (4126c647922e2e4a7318abfd725fc80621f61d90)

Mekanism:
- [x] Support for Energized Smelter (231f25eec4e54b798210132c78baed9b83df2dd2)
- [x] Support for Solar Evaporation Plant (231f25eec4e54b798210132c78baed9b83df2dd2)
- [x] Support for Solar Neutron Activator (231f25eec4e54b798210132c78baed9b83df2dd2)
- [ ] ~~Support for Rotary Condensentrator~~

Bugfixes:
- [x] ModTweaker 0.9.0 is not working properly if Botania is not loaded (a69971aca581bfa2a786d9f382404e97c694efc2)
- [x] Handler for Thermionic Fabricator throws NullPointerException (#188, 79021f05e5bb20bba2e456744eef2f2abff41731)
- [x] When using Thaumcraft handlers an error message will be thrown (#194, 269abc5750341687569e0f4ebd0f234bd6d1a047)
- [x] The handler for removing Mekanism Metallurgic Infuser recipes can't be invoked (#196, eeba6a3390c79cbd9d745eede25d1b70b5d266ef)

**Comment by Yulife** [comment]
Should Botania flowers get a custom bracket handler as well? :)

**Comment by jaredlll08** [comment]
... I implemented that, remember? you begged me to swap back to strings...

**Comment by Yulife** [comment]
Uhhh really? Mhm.

**Comment by Zixxl** [comment]
I'll release a new version with the bugfixes today, the features for thaumcraft aspect handler and WeightedItemStack have to wait one more release.
