### ISSUE TITLE
Planned Features for ModTweaker2 0.9.2

### ISSUE THREAD

**Issue by Zixxl** [jaredlll08/ModTweaker2#197]
Forestry
- [x] Ore dictionary support for Forestry Carpenter (#192)
- [x] Fermenter fuel support
- [x] Moistener fuel support

Railcraft
- [x] Support for BlastFurnace fuels (#193)

Thaumcraft:
- [x] Add aspect bracket handler (e.g. ```<aspect:Vitreus> * 5```) (99bd8eaa1ebd563b355e42ef9c8cf97b942a15e8)

Bugfixes:
- [x] Handler for AE2 Inscriber always returns error messages about missing parameters. (#200, acf41557a8259f5e8ff3e9cb61d17532f36db1f5) 
- [x] Wrong map reference for Mekanism Chemical Infuser (#213, e79a0fb1c4d36130f89481791c19368e22b3de6d)
- [x] Annotation missing in Mekanism Sawmill handler (#215, 91f47fc99491f1360efe5b989f5d91b62dd24c03)
- [x] ExNihilo heat sources can't be removed (#225, 8eb85f10223f0df7bd63cc1460a5735455e749eb)

**Comment by Voidi** [comment]
@Zixxl i think we should take about stack equality and stacksize

**Comment by kotoroshinoto** [comment]
with the build from Oct 1, I still get a Cannot cast minetweaker.oredict.IoreDictEntry to minetweaker.item.IItemStack error
